'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ship_Passenger_Ticketing_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _038422_glossy_black_icon_transport_travel_transportation_cruise_ship() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("038422-glossy-black-icon-transport-travel-transportation-cruise-ship", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _039040_green_jelly_icon_transport_travel_transportation_cruise_ship() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("039040-green-jelly-icon-transport-travel-transportation-cruise-ship", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _04066_dorsetdurdledoor_2048x1280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("04066_dorsetdurdledoor_2048x1280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1484031566_SDKs_copy_AWS_Toolkit_for_Visual_Studio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1484031566_SDKs_copy_AWS_Toolkit_for_Visual_Studio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1484031676_Non_Service_Specific_copy_Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1484031676_Non-Service_Specific_copy_Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1484031864_Vector_icons_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1484031864_Vector-icons_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1971882_1366x768__DesktopNexus_com_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1971882-1366x768-[DesktopNexus.com]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2048769_1366x768__DesktopNexus_com_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2048769-1366x768-[DesktopNexus.com]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _26248047840_67bc4df8a8_b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("26248047840_67bc4df8a8_b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6276266984_2ab52c6fd8_b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6276266984_2ab52c6fd8_b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a4ec09ea1091ab7dd868d9b1513e8892() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a4ec09ea1091ab7dd868d9b1513e8892", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajax_loader_200x200_trans_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax-loader_200x200_trans_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property analytics_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("analytics-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apple_slogan_wallpaper_2560x1440() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apple_slogan-wallpaper-2560x1440", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apple_slogan_wallpaper_2560x14401() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apple_slogan-wallpaper-2560x14401", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved_Images_images_6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C__Data_Users_DefApps_AppData_INTERNETEXPLORER_Temp_Saved Images_images(6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dpd_logo_white2015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpd-logo-white2015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvd_box_icon_52196() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd-box-icon-52196", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property get_discount_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("get_discount-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (11)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__18_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (18)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__18_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (18)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__32_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (32)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__49_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (49)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__51_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (51)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images-6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesship2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesship2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IMG_20170105_184557_412() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20170105_184557_412", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property install_install_icon_36314() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("install-install-icon-36314", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kreuz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kreuz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loader__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_ocean_shipping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-ocean-shipping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marvel___the_avengers_shield_logo_wallpaper_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marvel___the_avengers_shield_logo-wallpaper-1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marvel___the_avengers_shield_logo_wallpaper_1920x10801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marvel___the_avengers_shield_logo-wallpaper-1920x10801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MMM3_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MMM3-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property partnership_logos_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("partnership_logos_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ps_playstation_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ps_playstation_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ps_playstation_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ps_playstation_logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Screenshot__62_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot (62)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SE_logo_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SE_logo_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SE_logo_green1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SE_logo_green1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property software_grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("software-grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property support_loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("support-loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unnamed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unnamed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unnamed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unnamed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
